# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-05 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('donation', models.DecimalField(decimal_places=2, default='5.00', max_digits=9)),
                ('minDonation', models.DecimalField(decimal_places=2, default='5.00', max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='DonationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40)),
                ('amount_donated', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('donation_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.DonationInformation')),
                ('donations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donation.Donation')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
