# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-26 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HappyEnding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('adoption_date', models.CharField(default='', max_length=20)),
                ('adoption_image', models.ImageField(blank=True, upload_to='adoption_images/')),
            ],
        ),
    ]
