# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('age', models.CharField(default='unknown', max_length=100)),
                ('breed', models.CharField(default='mix breed', max_length=100)),
                ('date_of_birth', models.CharField(default='unknown', max_length=100)),
                ('in_shelter_from', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('dog_image1', models.ImageField(blank=True, upload_to='dog_images')),
                ('dog_image2', models.ImageField(blank=True, null=True, upload_to='dog_images')),
            ],
        ),
    ]
