# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('age', models.CharField(default='Unknown', max_length=100)),
                ('breed', models.CharField(default='Mix breed', max_length=100)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=100)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Small', max_length=100)),
                ('situation', models.CharField(choices=[('At foster family', 'At foster family'), ('In shelter', 'In shelter')], default='In shelter', max_length=100)),
                ('location', models.CharField(choices=[('Spain', 'Spain'), ('The Netherlands', 'The Netherlands')], default='Spain', max_length=100)),
                ('status', models.BooleanField(default=True, verbose_name='For adoption')),
                ('date_of_birth', models.DateField(max_length=8)),
                ('in_shelter_from', models.CharField(default='', max_length=100)),
                ('dog_image1', models.ImageField(blank=True, upload_to='dog_images/')),
                ('dog_image2', models.ImageField(blank=True, null=True, upload_to='dog_images/')),
                ('dog_image3', models.ImageField(blank=True, null=True, upload_to='dog_images/')),
                ('dog_image4', models.ImageField(blank=True, null=True, upload_to='dog_images/')),
            ],
        ),
    ]
