# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-07 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptable',
            name='status',
            field=models.BooleanField(default=True, verbose_name='For adoption'),
        ),
    ]
