# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-26 18:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptable',
            name='date_of_birth',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='in_shelter_from',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11), null=True),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='status',
            field=models.BooleanField(verbose_name='For adoption'),
        ),
    ]
