# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-26 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptables', '0002_auto_20200126_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptable',
            name='age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='date_of_birth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='in_shelter_from',
            field=models.CharField(default='', max_length=100),
        ),
    ]
