# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-10 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptables', '0003_adoptable_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptable',
            name='dog_image3',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images'),
        ),
        migrations.AddField(
            model_name='adoptable',
            name='dog_image4',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images'),
        ),
        migrations.AddField(
            model_name='adoptable',
            name='situation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adoptable',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='age',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='breed',
            field=models.CharField(default='Mix breed', max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='date_of_birth',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
