# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-03 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptables', '0003_auto_20200126_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptable',
            name='breed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='date_of_birth',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='in_shelter_from',
            field=models.CharField(default='', max_length=20),
        ),
    ]
