# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptables', '0004_auto_20200203_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptable',
            name='status',
            field=models.BooleanField(default='True', verbose_name='For adoption'),
        ),
    ]
