# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-23 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptables', '0004_auto_20200110_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptable',
            name='dog_image1',
            field=models.ImageField(blank=True, upload_to='dog_images/'),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='dog_image2',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images/'),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='dog_image3',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images/'),
        ),
        migrations.AlterField(
            model_name='adoptable',
            name='dog_image4',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images/'),
        ),
    ]
