# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-25 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoptables', '0005_auto_20200123_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptable',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
