# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-25 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoptables', '0006_adoptable_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptable',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
