# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-25 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptables', '0007_auto_20200125_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptable',
            name='author',
        ),
    ]
