# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-25 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptables', '0009_adoptable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptable',
            name='user',
        ),
    ]
